name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mm404/mkdocs:$(date +%Y%m%d) --tag mm404/mkdocs:latest
    - name: Test container
      run: docker run -it mm404/mkdocs:latest /usr/local/bin/mkdocs --help
    - name: Log in to Docker hub
      if: github.event_name == 'push'
      run: echo ${{ secrets.DOCKER_HUB_KEY }} | docker login -u mm404 --password-stdin
    - name: Push image to Docker
      if: github.event_name == 'push'
      run: docker push -a mm404/mkdocs
    
